// <auto-generated />
using System;
using Academic.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Academic.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AcademicDbContext))]
    [Migration("20260306053145_InitialCodeFirst")]
    partial class InitialCodeFirst
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Academic.Infrastructure.Persistence.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_name");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("audit_logs_pkey");

                    b.HasIndex(new[] { "EntityName", "EntityId", "CreatedAt" }, "idx_audit_logs_entity_created")
                        .IsDescending(false, false, true);

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "idx_audit_logs_user_created")
                        .IsDescending(false, true);

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.Campus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)")
                        .HasColumnName("address");

                    b.Property<string>("CampusType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("campus_type")
                        .HasDefaultValueSql("'Campus'::character varying");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("region");

                    b.HasKey("Id")
                        .HasName("campuses_pkey");

                    b.HasIndex(new[] { "Code" }, "campuses_code_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "campuses_name_key")
                        .IsUnique();

                    b.HasIndex(new[] { "CampusType", "Region" }, "idx_campuses_type_region");

                    b.ToTable("campuses", (string)null);
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.CampusShiftCapacity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CampusId")
                        .HasColumnType("integer")
                        .HasColumnName("campus_id");

                    b.Property<int>("OccupiedCapacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("occupied_capacity");

                    b.Property<short>("ShiftId")
                        .HasColumnType("smallint")
                        .HasColumnName("shift_id");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("total_capacity");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("campus_shift_capacity_pkey");

                    b.HasIndex("ShiftId");

                    b.HasIndex(new[] { "CampusId", "ShiftId" }, "uq_campus_shift")
                        .IsUnique();

                    b.ToTable("campus_shift_capacity", (string)null);
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.CarnetPrefixCatalog", b =>
                {
                    b.Property<string>("Prefix")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("prefix");

                    b.Property<int>("CampusId")
                        .HasColumnType("integer")
                        .HasColumnName("campus_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("ProgramId")
                        .HasColumnType("integer")
                        .HasColumnName("program_id");

                    b.Property<short>("ShiftId")
                        .HasColumnType("smallint")
                        .HasColumnName("shift_id");

                    b.HasKey("Prefix")
                        .HasName("carnet_prefix_catalog_pkey");

                    b.HasIndex(new[] { "CampusId" }, "idx_carnet_prefix_campus_id");

                    b.HasIndex(new[] { "ProgramId" }, "idx_carnet_prefix_program_id");

                    b.HasIndex(new[] { "ShiftId" }, "idx_carnet_prefix_shift_id");

                    b.ToTable("carnet_prefix_catalog", (string)null);
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("PaymentOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_order_id");

                    b.Property<string>("PdfPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pdf_path");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("purpose");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("verification_code");

                    b.HasKey("Id")
                        .HasName("certificates_pkey");

                    b.HasIndex(new[] { "PaymentOrderId" }, "certificates_payment_order_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "VerificationCode" }, "certificates_verification_code_key")
                        .IsUnique();

                    b.HasIndex(new[] { "VerificationCode" }, "idx_certificates_code");

                    b.HasIndex(new[] { "StudentId", "Status" }, "idx_certificates_student_status");

                    b.HasIndex(new[] { "StudentId" }, "uq_certificate_active_per_student")
                        .IsUnique()
                        .HasFilter("((status)::text = ANY ((ARRAY['Requested'::character varying, 'PdfGenerated'::character varying])::text[]))");

                    b.ToTable("certificates", (string)null);
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("Credits")
                        .HasColumnType("smallint")
                        .HasColumnName("credits");

                    b.Property<short>("Cycle")
                        .HasColumnType("smallint")
                        .HasColumnName("cycle");

                    b.Property<short>("HoursPerWeek")
                        .HasColumnType("smallint")
                        .HasColumnName("hours_per_week");

                    b.Property<short>("HoursTotal")
                        .HasColumnType("smallint")
                        .HasColumnName("hours_total");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsLab")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_lab");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<int>("ProgramId")
                        .HasColumnType("integer")
                        .HasColumnName("program_id");

                    b.HasKey("Id")
                        .HasName("courses_pkey");

                    b.HasIndex(new[] { "Code" }, "courses_code_key")
                        .IsUnique();

                    b.HasIndex(new[] { "ProgramId", "Cycle" }, "idx_courses_program_cycle");

                    b.HasIndex(new[] { "ProgramId" }, "idx_courses_program_id");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.CourseCreditRequirement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("MinApprovedCredits")
                        .HasColumnType("smallint")
                        .HasColumnName("min_approved_credits");

                    b.HasKey("Id")
                        .HasName("course_credit_requirements_pkey");

                    b.HasIndex(new[] { "CourseId" }, "idx_course_credit_requirements_course_id");

                    b.ToTable("course_credit_requirements", (string)null);
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EnrollmentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("enrollment_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("enrollments_pkey");

                    b.HasIndex(new[] { "StudentId", "Status" }, "idx_enrollments_student_status");

                    b.HasIndex(new[] { "StudentId" }, "uq_enrollment_active_per_student")
                        .IsUnique()
                        .HasFilter("((status)::text = 'PendingPayment'::text)");

                    b.ToTable("enrollments", (string)null);
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.EnrollmentCourse", b =>
                {
                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("enrollment_id");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<bool>("IsOverdue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_overdue");

                    b.HasKey("EnrollmentId", "CourseId")
                        .HasName("enrollment_courses_pkey");

                    b.HasIndex("CourseId");

                    b.ToTable("enrollment_courses", (string)null);
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.PaymentOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency")
                        .HasDefaultValueSql("'GTQ'::character varying");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<DateTime>("ExpiresAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at")
                        .HasDefaultValueSql("(now() + '72:00:00'::interval)");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("order_type");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("payment_orders_pkey");

                    b.HasIndex(new[] { "ReferenceId", "OrderType" }, "idx_payment_orders_reference");

                    b.HasIndex(new[] { "Status", "ExpiresAt" }, "idx_payment_orders_status_expires");

                    b.HasIndex(new[] { "StudentId", "Status" }, "idx_payment_orders_student_status");

                    b.HasIndex(new[] { "OrderType", "ReferenceId" }, "uq_payment_reference")
                        .IsUnique();

                    b.ToTable("payment_orders", (string)null);
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.PricingCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency")
                        .HasDefaultValueSql("'GTQ'::character varying");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int?>("ProgramId")
                        .HasColumnType("integer")
                        .HasColumnName("program_id");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("service_type");

                    b.HasKey("Id")
                        .HasName("pricing_catalog_pkey");

                    b.HasIndex("ProgramId");

                    b.ToTable("pricing_catalog", (string)null);
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.Program", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("programs_pkey");

                    b.HasIndex(new[] { "Code" }, "programs_code_key")
                        .IsUnique();

                    b.ToTable("programs", (string)null);
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.Role", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "Name" }, "roles_name_key")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.Shift", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("shifts_pkey");

                    b.HasIndex(new[] { "Name" }, "shifts_name_key")
                        .IsUnique();

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Carnet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("carnet");

                    b.Property<string>("CarnetPrefix")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("carnet_prefix");

                    b.Property<string>("CarnetSequence")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("carnet_sequence");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("CurrentCampusId")
                        .HasColumnType("integer")
                        .HasColumnName("current_campus_id");

                    b.Property<short?>("CurrentShiftId")
                        .HasColumnType("smallint")
                        .HasColumnName("current_shift_id");

                    b.Property<short>("EntryYear")
                        .HasColumnType("smallint")
                        .HasColumnName("entry_year");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("first_name");

                    b.Property<string>("InstitutionalEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("institutional_email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("last_name");

                    b.Property<int>("ProgramId")
                        .HasColumnType("integer")
                        .HasColumnName("program_id");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("student_code");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("students_pkey");

                    b.HasIndex("CarnetPrefix");

                    b.HasIndex("CurrentCampusId");

                    b.HasIndex("CurrentShiftId");

                    b.HasIndex(new[] { "ProgramId" }, "idx_students_program_id");

                    b.HasIndex(new[] { "UserId" }, "idx_students_user_id");

                    b.HasIndex(new[] { "Carnet" }, "students_carnet_key")
                        .IsUnique();

                    b.HasIndex(new[] { "InstitutionalEmail" }, "students_institutional_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "StudentCode" }, "students_student_code_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "students_user_id_key")
                        .IsUnique();

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.StudentCourseHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("Grade")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("grade");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("term");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("student_course_history_pkey");

                    b.HasIndex(new[] { "CourseId", "StudentId" }, "idx_history_course_student");

                    b.HasIndex(new[] { "StudentId", "Status" }, "idx_history_student_status");

                    b.ToTable("student_course_history", (string)null);
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.TransferRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("FromCampusId")
                        .HasColumnType("integer")
                        .HasColumnName("from_campus_id");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("modality");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("review_notes");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<int>("ToCampusId")
                        .HasColumnType("integer")
                        .HasColumnName("to_campus_id");

                    b.Property<short>("ToShiftId")
                        .HasColumnType("smallint")
                        .HasColumnName("to_shift_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("transfer_requests_pkey");

                    b.HasIndex("FromCampusId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("ToShiftId");

                    b.HasIndex(new[] { "ToCampusId", "ToShiftId", "Status" }, "idx_transfers_destination");

                    b.HasIndex(new[] { "StudentId", "Status" }, "idx_transfers_student_status");

                    b.HasIndex(new[] { "StudentId" }, "uq_transfer_active_per_student")
                        .IsUnique()
                        .HasFilter("((status)::text = ANY ((ARRAY['PendingPayment'::character varying, 'PendingReview'::character varying])::text[]))");

                    b.ToTable("transfer_requests", (string)null);
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "idx_users_email");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "RoleId")
                        .HasName("user_roles_pkey");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("CoursePrerequisite", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<int>("PrerequisiteCourseId")
                        .HasColumnType("integer")
                        .HasColumnName("prerequisite_course_id");

                    b.HasKey("CourseId", "PrerequisiteCourseId")
                        .HasName("course_prerequisites_pkey");

                    b.HasIndex("PrerequisiteCourseId");

                    b.ToTable("course_prerequisites", (string)null);
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.AuditLog", b =>
                {
                    b.HasOne("Academic.Infrastructure.Persistence.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("audit_logs_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.CampusShiftCapacity", b =>
                {
                    b.HasOne("Academic.Infrastructure.Persistence.Campus", "Campus")
                        .WithMany("CampusShiftCapacities")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("campus_shift_capacity_campus_id_fkey");

                    b.HasOne("Academic.Infrastructure.Persistence.Shift", "Shift")
                        .WithMany("CampusShiftCapacities")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("campus_shift_capacity_shift_id_fkey");

                    b.Navigation("Campus");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.CarnetPrefixCatalog", b =>
                {
                    b.HasOne("Academic.Infrastructure.Persistence.Campus", "Campus")
                        .WithMany("CarnetPrefixCatalogs")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("carnet_prefix_catalog_campus_id_fkey");

                    b.HasOne("Academic.Infrastructure.Persistence.Program", "Program")
                        .WithMany("CarnetPrefixCatalogs")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("carnet_prefix_catalog_program_id_fkey");

                    b.HasOne("Academic.Infrastructure.Persistence.Shift", "Shift")
                        .WithMany("CarnetPrefixCatalogs")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("carnet_prefix_catalog_shift_id_fkey");

                    b.Navigation("Campus");

                    b.Navigation("Program");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.Certificate", b =>
                {
                    b.HasOne("Academic.Infrastructure.Persistence.PaymentOrder", "PaymentOrder")
                        .WithOne("Certificate")
                        .HasForeignKey("Academic.Infrastructure.Persistence.Certificate", "PaymentOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("certificates_payment_order_id_fkey");

                    b.HasOne("Academic.Infrastructure.Persistence.Student", "Student")
                        .WithMany("Certificates")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("certificates_student_id_fkey");

                    b.Navigation("PaymentOrder");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.Course", b =>
                {
                    b.HasOne("Academic.Infrastructure.Persistence.Program", "Program")
                        .WithMany("Courses")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("courses_program_id_fkey");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.CourseCreditRequirement", b =>
                {
                    b.HasOne("Academic.Infrastructure.Persistence.Course", "Course")
                        .WithMany("CourseCreditRequirements")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("course_credit_requirements_course_id_fkey");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.Enrollment", b =>
                {
                    b.HasOne("Academic.Infrastructure.Persistence.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("enrollments_student_id_fkey");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.EnrollmentCourse", b =>
                {
                    b.HasOne("Academic.Infrastructure.Persistence.Course", "Course")
                        .WithMany("EnrollmentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("enrollment_courses_course_id_fkey");

                    b.HasOne("Academic.Infrastructure.Persistence.Enrollment", "Enrollment")
                        .WithMany("EnrollmentCourses")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("enrollment_courses_enrollment_id_fkey");

                    b.Navigation("Course");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.PaymentOrder", b =>
                {
                    b.HasOne("Academic.Infrastructure.Persistence.Student", "Student")
                        .WithMany("PaymentOrders")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("payment_orders_student_id_fkey");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.PricingCatalog", b =>
                {
                    b.HasOne("Academic.Infrastructure.Persistence.Program", "Program")
                        .WithMany("PricingCatalogs")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("pricing_catalog_program_id_fkey");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.Student", b =>
                {
                    b.HasOne("Academic.Infrastructure.Persistence.CarnetPrefixCatalog", "CarnetPrefixNavigation")
                        .WithMany("Students")
                        .HasForeignKey("CarnetPrefix")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("students_carnet_prefix_fkey");

                    b.HasOne("Academic.Infrastructure.Persistence.Campus", "CurrentCampus")
                        .WithMany("Students")
                        .HasForeignKey("CurrentCampusId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("students_current_campus_id_fkey");

                    b.HasOne("Academic.Infrastructure.Persistence.Shift", "CurrentShift")
                        .WithMany("Students")
                        .HasForeignKey("CurrentShiftId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("students_current_shift_id_fkey");

                    b.HasOne("Academic.Infrastructure.Persistence.Program", "Program")
                        .WithMany("Students")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("students_program_id_fkey");

                    b.HasOne("Academic.Infrastructure.Persistence.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("Academic.Infrastructure.Persistence.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("students_user_id_fkey");

                    b.Navigation("CarnetPrefixNavigation");

                    b.Navigation("CurrentCampus");

                    b.Navigation("CurrentShift");

                    b.Navigation("Program");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.StudentCourseHistory", b =>
                {
                    b.HasOne("Academic.Infrastructure.Persistence.Course", "Course")
                        .WithMany("StudentCourseHistories")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("student_course_history_course_id_fkey");

                    b.HasOne("Academic.Infrastructure.Persistence.Student", "Student")
                        .WithMany("StudentCourseHistories")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("student_course_history_student_id_fkey");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.TransferRequest", b =>
                {
                    b.HasOne("Academic.Infrastructure.Persistence.Campus", "FromCampus")
                        .WithMany("TransferRequestFromCampuses")
                        .HasForeignKey("FromCampusId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("transfer_requests_from_campus_id_fkey");

                    b.HasOne("Academic.Infrastructure.Persistence.User", "ReviewedByUser")
                        .WithMany("TransferRequests")
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("transfer_requests_reviewed_by_user_id_fkey");

                    b.HasOne("Academic.Infrastructure.Persistence.Student", "Student")
                        .WithMany("TransferRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("transfer_requests_student_id_fkey");

                    b.HasOne("Academic.Infrastructure.Persistence.Campus", "ToCampus")
                        .WithMany("TransferRequestToCampuses")
                        .HasForeignKey("ToCampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("transfer_requests_to_campus_id_fkey");

                    b.HasOne("Academic.Infrastructure.Persistence.Shift", "ToShift")
                        .WithMany("TransferRequests")
                        .HasForeignKey("ToShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("transfer_requests_to_shift_id_fkey");

                    b.Navigation("FromCampus");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("Student");

                    b.Navigation("ToCampus");

                    b.Navigation("ToShift");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.UserRole", b =>
                {
                    b.HasOne("Academic.Infrastructure.Persistence.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("user_roles_role_id_fkey");

                    b.HasOne("Academic.Infrastructure.Persistence.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_roles_user_id_fkey");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoursePrerequisite", b =>
                {
                    b.HasOne("Academic.Infrastructure.Persistence.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("course_prerequisites_course_id_fkey");

                    b.HasOne("Academic.Infrastructure.Persistence.Course", null)
                        .WithMany()
                        .HasForeignKey("PrerequisiteCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("course_prerequisites_prerequisite_course_id_fkey");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.Campus", b =>
                {
                    b.Navigation("CampusShiftCapacities");

                    b.Navigation("CarnetPrefixCatalogs");

                    b.Navigation("Students");

                    b.Navigation("TransferRequestFromCampuses");

                    b.Navigation("TransferRequestToCampuses");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.CarnetPrefixCatalog", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.Course", b =>
                {
                    b.Navigation("CourseCreditRequirements");

                    b.Navigation("EnrollmentCourses");

                    b.Navigation("StudentCourseHistories");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.Enrollment", b =>
                {
                    b.Navigation("EnrollmentCourses");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.PaymentOrder", b =>
                {
                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.Program", b =>
                {
                    b.Navigation("CarnetPrefixCatalogs");

                    b.Navigation("Courses");

                    b.Navigation("PricingCatalogs");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.Shift", b =>
                {
                    b.Navigation("CampusShiftCapacities");

                    b.Navigation("CarnetPrefixCatalogs");

                    b.Navigation("Students");

                    b.Navigation("TransferRequests");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.Student", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Enrollments");

                    b.Navigation("PaymentOrders");

                    b.Navigation("StudentCourseHistories");

                    b.Navigation("TransferRequests");
                });

            modelBuilder.Entity("Academic.Infrastructure.Persistence.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Student");

                    b.Navigation("TransferRequests");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
