CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE EXTENSION IF NOT EXISTS pgcrypto;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE TABLE campuses (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        code character varying(20) NOT NULL,
        name character varying(180) NOT NULL,
        address character varying(280) NOT NULL,
        is_active boolean NOT NULL DEFAULT TRUE,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        campus_type character varying(20) NOT NULL DEFAULT ('Campus'::character varying),
        region character varying(60),
        CONSTRAINT campuses_pkey PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE TABLE programs (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        code character varying(20) NOT NULL,
        name character varying(180) NOT NULL,
        is_active boolean NOT NULL DEFAULT TRUE,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT programs_pkey PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE TABLE roles (
        id smallint GENERATED BY DEFAULT AS IDENTITY,
        name character varying(32) NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT roles_pkey PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE TABLE shifts (
        id smallint GENERATED BY DEFAULT AS IDENTITY,
        name character varying(20) NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT shifts_pkey PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE TABLE users (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        email character varying(255) NOT NULL,
        password_hash character varying(255) NOT NULL,
        is_active boolean NOT NULL DEFAULT TRUE,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        updated_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT users_pkey PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE TABLE courses (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        program_id integer NOT NULL,
        code character varying(20) NOT NULL,
        name character varying(180) NOT NULL,
        credits smallint NOT NULL,
        cycle smallint NOT NULL,
        hours_per_week smallint NOT NULL,
        hours_total smallint NOT NULL,
        is_lab boolean NOT NULL DEFAULT FALSE,
        is_active boolean NOT NULL DEFAULT TRUE,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT courses_pkey PRIMARY KEY (id),
        CONSTRAINT courses_program_id_fkey FOREIGN KEY (program_id) REFERENCES programs (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE TABLE pricing_catalog (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        service_type character varying(30) NOT NULL,
        program_id integer,
        amount numeric(12,2) NOT NULL,
        currency character varying(3) NOT NULL DEFAULT ('GTQ'::character varying),
        is_active boolean NOT NULL DEFAULT TRUE,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT pricing_catalog_pkey PRIMARY KEY (id),
        CONSTRAINT pricing_catalog_program_id_fkey FOREIGN KEY (program_id) REFERENCES programs (id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE TABLE campus_shift_capacity (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        campus_id integer NOT NULL,
        shift_id smallint NOT NULL,
        total_capacity integer NOT NULL,
        occupied_capacity integer NOT NULL DEFAULT 0,
        updated_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT campus_shift_capacity_pkey PRIMARY KEY (id),
        CONSTRAINT campus_shift_capacity_campus_id_fkey FOREIGN KEY (campus_id) REFERENCES campuses (id) ON DELETE RESTRICT,
        CONSTRAINT campus_shift_capacity_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES shifts (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE TABLE carnet_prefix_catalog (
        prefix character varying(4) NOT NULL,
        program_id integer NOT NULL,
        campus_id integer NOT NULL,
        shift_id smallint NOT NULL,
        description character varying(180) NOT NULL,
        is_active boolean NOT NULL DEFAULT TRUE,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT carnet_prefix_catalog_pkey PRIMARY KEY (prefix),
        CONSTRAINT carnet_prefix_catalog_campus_id_fkey FOREIGN KEY (campus_id) REFERENCES campuses (id) ON DELETE RESTRICT,
        CONSTRAINT carnet_prefix_catalog_program_id_fkey FOREIGN KEY (program_id) REFERENCES programs (id) ON DELETE RESTRICT,
        CONSTRAINT carnet_prefix_catalog_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES shifts (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE TABLE audit_logs (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_id uuid,
        action character varying(100) NOT NULL,
        entity_name character varying(100) NOT NULL,
        entity_id character varying(100) NOT NULL,
        details jsonb,
        ip_address character varying(64),
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
        CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE TABLE user_roles (
        user_id uuid NOT NULL,
        role_id smallint NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id),
        CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT,
        CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE TABLE course_credit_requirements (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        course_id integer NOT NULL,
        min_approved_credits smallint NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT course_credit_requirements_pkey PRIMARY KEY (id),
        CONSTRAINT course_credit_requirements_course_id_fkey FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE TABLE course_prerequisites (
        course_id integer NOT NULL,
        prerequisite_course_id integer NOT NULL,
        CONSTRAINT course_prerequisites_pkey PRIMARY KEY (course_id, prerequisite_course_id),
        CONSTRAINT course_prerequisites_course_id_fkey FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
        CONSTRAINT course_prerequisites_prerequisite_course_id_fkey FOREIGN KEY (prerequisite_course_id) REFERENCES courses (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE TABLE students (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        user_id uuid NOT NULL,
        student_code character varying(30) NOT NULL,
        institutional_email character varying(255) NOT NULL,
        first_name character varying(120) NOT NULL,
        last_name character varying(120) NOT NULL,
        carnet character varying(20) NOT NULL,
        carnet_prefix character varying(4) NOT NULL,
        entry_year smallint NOT NULL,
        carnet_sequence character varying(5) NOT NULL,
        program_id integer NOT NULL,
        current_campus_id integer,
        current_shift_id smallint,
        is_active boolean NOT NULL DEFAULT TRUE,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        updated_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT students_pkey PRIMARY KEY (id),
        CONSTRAINT students_carnet_prefix_fkey FOREIGN KEY (carnet_prefix) REFERENCES carnet_prefix_catalog (prefix) ON DELETE RESTRICT,
        CONSTRAINT students_current_campus_id_fkey FOREIGN KEY (current_campus_id) REFERENCES campuses (id) ON DELETE SET NULL,
        CONSTRAINT students_current_shift_id_fkey FOREIGN KEY (current_shift_id) REFERENCES shifts (id) ON DELETE SET NULL,
        CONSTRAINT students_program_id_fkey FOREIGN KEY (program_id) REFERENCES programs (id) ON DELETE RESTRICT,
        CONSTRAINT students_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE TABLE enrollments (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        student_id uuid NOT NULL,
        enrollment_type character varying(20) NOT NULL,
        status character varying(30) NOT NULL,
        total_amount numeric(12,2) NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        updated_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT enrollments_pkey PRIMARY KEY (id),
        CONSTRAINT enrollments_student_id_fkey FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE TABLE payment_orders (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        student_id uuid NOT NULL,
        order_type character varying(20) NOT NULL,
        reference_id uuid NOT NULL,
        amount numeric(12,2) NOT NULL,
        status character varying(20) NOT NULL,
        description character varying(255) NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        paid_at timestamp with time zone,
        cancelled_at timestamp with time zone,
        currency character varying(3) NOT NULL DEFAULT ('GTQ'::character varying),
        expires_at timestamp with time zone NOT NULL DEFAULT ((now() + '72:00:00'::interval)),
        CONSTRAINT payment_orders_pkey PRIMARY KEY (id),
        CONSTRAINT payment_orders_student_id_fkey FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE TABLE student_course_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        student_id uuid NOT NULL,
        course_id integer NOT NULL,
        year smallint NOT NULL,
        term character varying(20) NOT NULL,
        grade numeric(5,2),
        status character varying(20) NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT student_course_history_pkey PRIMARY KEY (id),
        CONSTRAINT student_course_history_course_id_fkey FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE RESTRICT,
        CONSTRAINT student_course_history_student_id_fkey FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE TABLE transfer_requests (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        student_id uuid NOT NULL,
        from_campus_id integer,
        to_campus_id integer NOT NULL,
        to_shift_id smallint NOT NULL,
        modality character varying(20) NOT NULL,
        reason character varying(500),
        status character varying(30) NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        updated_at timestamp with time zone NOT NULL DEFAULT (now()),
        reviewed_by_user_id uuid,
        reviewed_at timestamp with time zone,
        review_notes character varying(500),
        CONSTRAINT transfer_requests_pkey PRIMARY KEY (id),
        CONSTRAINT transfer_requests_from_campus_id_fkey FOREIGN KEY (from_campus_id) REFERENCES campuses (id) ON DELETE SET NULL,
        CONSTRAINT transfer_requests_reviewed_by_user_id_fkey FOREIGN KEY (reviewed_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
        CONSTRAINT transfer_requests_student_id_fkey FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE,
        CONSTRAINT transfer_requests_to_campus_id_fkey FOREIGN KEY (to_campus_id) REFERENCES campuses (id) ON DELETE RESTRICT,
        CONSTRAINT transfer_requests_to_shift_id_fkey FOREIGN KEY (to_shift_id) REFERENCES shifts (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE TABLE enrollment_courses (
        enrollment_id uuid NOT NULL,
        course_id integer NOT NULL,
        is_overdue boolean NOT NULL DEFAULT FALSE,
        CONSTRAINT enrollment_courses_pkey PRIMARY KEY (enrollment_id, course_id),
        CONSTRAINT enrollment_courses_course_id_fkey FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE RESTRICT,
        CONSTRAINT enrollment_courses_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES enrollments (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE TABLE certificates (
        id uuid NOT NULL DEFAULT (gen_random_uuid()),
        student_id uuid NOT NULL,
        payment_order_id uuid NOT NULL,
        purpose character varying(255) NOT NULL,
        status character varying(30) NOT NULL,
        verification_code character varying(60) NOT NULL,
        pdf_path character varying(500),
        metadata jsonb,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        generated_at timestamp with time zone,
        sent_at timestamp with time zone,
        CONSTRAINT certificates_pkey PRIMARY KEY (id),
        CONSTRAINT certificates_payment_order_id_fkey FOREIGN KEY (payment_order_id) REFERENCES payment_orders (id) ON DELETE RESTRICT,
        CONSTRAINT certificates_student_id_fkey FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX idx_audit_logs_entity_created ON audit_logs (entity_name, entity_id, created_at DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX idx_audit_logs_user_created ON audit_logs (user_id, created_at DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX "IX_campus_shift_capacity_shift_id" ON campus_shift_capacity (shift_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE UNIQUE INDEX uq_campus_shift ON campus_shift_capacity (campus_id, shift_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE UNIQUE INDEX campuses_code_key ON campuses (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE UNIQUE INDEX campuses_name_key ON campuses (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX idx_campuses_type_region ON campuses (campus_type, region);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX idx_carnet_prefix_campus_id ON carnet_prefix_catalog (campus_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX idx_carnet_prefix_program_id ON carnet_prefix_catalog (program_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX idx_carnet_prefix_shift_id ON carnet_prefix_catalog (shift_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE UNIQUE INDEX certificates_payment_order_id_key ON certificates (payment_order_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE UNIQUE INDEX certificates_verification_code_key ON certificates (verification_code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX idx_certificates_code ON certificates (verification_code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX idx_certificates_student_status ON certificates (student_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE UNIQUE INDEX uq_certificate_active_per_student ON certificates (student_id) WHERE ((status)::text = ANY ((ARRAY['Requested'::character varying, 'PdfGenerated'::character varying])::text[]));
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX idx_course_credit_requirements_course_id ON course_credit_requirements (course_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX "IX_course_prerequisites_prerequisite_course_id" ON course_prerequisites (prerequisite_course_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE UNIQUE INDEX courses_code_key ON courses (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX idx_courses_program_cycle ON courses (program_id, cycle);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX idx_courses_program_id ON courses (program_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX "IX_enrollment_courses_course_id" ON enrollment_courses (course_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX idx_enrollments_student_status ON enrollments (student_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE UNIQUE INDEX uq_enrollment_active_per_student ON enrollments (student_id) WHERE ((status)::text = 'PendingPayment'::text);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX idx_payment_orders_reference ON payment_orders (reference_id, order_type);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX idx_payment_orders_status_expires ON payment_orders (status, expires_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX idx_payment_orders_student_status ON payment_orders (student_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE UNIQUE INDEX uq_payment_reference ON payment_orders (order_type, reference_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX "IX_pricing_catalog_program_id" ON pricing_catalog (program_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE UNIQUE INDEX programs_code_key ON programs (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE UNIQUE INDEX roles_name_key ON roles (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE UNIQUE INDEX shifts_name_key ON shifts (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX idx_history_course_student ON student_course_history (course_id, student_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX idx_history_student_status ON student_course_history (student_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX idx_students_program_id ON students (program_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX idx_students_user_id ON students (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX "IX_students_carnet_prefix" ON students (carnet_prefix);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX "IX_students_current_campus_id" ON students (current_campus_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX "IX_students_current_shift_id" ON students (current_shift_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE UNIQUE INDEX students_carnet_key ON students (carnet);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE UNIQUE INDEX students_institutional_email_key ON students (institutional_email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE UNIQUE INDEX students_student_code_key ON students (student_code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE UNIQUE INDEX students_user_id_key ON students (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX idx_transfers_destination ON transfer_requests (to_campus_id, to_shift_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX idx_transfers_student_status ON transfer_requests (student_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX "IX_transfer_requests_from_campus_id" ON transfer_requests (from_campus_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX "IX_transfer_requests_reviewed_by_user_id" ON transfer_requests (reviewed_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX "IX_transfer_requests_to_shift_id" ON transfer_requests (to_shift_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE UNIQUE INDEX uq_transfer_active_per_student ON transfer_requests (student_id) WHERE ((status)::text = ANY ((ARRAY['PendingPayment'::character varying, 'PendingReview'::character varying])::text[]));
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX "IX_user_roles_role_id" ON user_roles (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE INDEX idx_users_email ON users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    CREATE UNIQUE INDEX users_email_key ON users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306053145_InitialCodeFirst') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260306053145_InitialCodeFirst', '8.0.8');
    END IF;
END $EF$;
COMMIT;

